export const ADD = 'ADD'
export const LOGIN_APP = 'LOGIN_APP'
export const LOGOUT_APP = 'LOGOUT_APP'
export const SIGNUP_APP = 'SIGNUP_APP'
export const GET_PROFILE = 'GET_PROFILE'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_TOKEN_LOCAL = 'SAVE_TOKEN_LOCAL'